name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
      - name: Run python black code formatter
        # You may pin to the exact commit or the version.
        # uses: DataDog/action-py-black-formatter@4aedfc9477c7c02cc6154936d2df964bb014a226
        uses: DataDog/action-py-black-formatter@v2.3
